# Generated by Django 5.1.2 on 2024-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
